version: '2'
services:
 phpcli:
   build:
     context: docker/phpcli
   working_dir: /var/www
   volumes:
    - .:/var/www

# Not be used in prod,, highly insecure passwords!
 database:
   image: 'mariadb/server:10.4'
   env_file:
     .dockerenv



