<?php
namespace WebOfTalent\Cache\Tests;

use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\SapphireTest;
use WebOfTalent\Cache\CacheKeyHelper;
use WebOfTalent\Cache\Tests\Model\TestArticle;
use WebOfTalent\Cache\Tests\Model\TestLink;

class CacheKeyHelperTest extends SapphireTest
{
    protected static $extra_dataobjects = [
        TestArticle::class,
        TestLink::class
    ];

    /**
     * @var CacheKeyHelper
     */
    private $ck;

    private $article;

    public function setUp()
    {
        Injector::nest();

        // create an article
        $this->article = new TestArticle();
        $this->article->Title = 'Test Caching Article';
        $this->article->write();

        // create a link
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        Injector::unnest();

    }

    public function testCacheParamKey()
    {
    }

    public function testCacheKeyGetParam()
    {
        $this->markTestSkipped('TODO');
    }

    public function testCacheKey()
    {
        $key = $this->article->CacheKey('article','WebOfTalent\Cache\Tests\Model\TestArticle');

    }

    public function testCacheDataKey()
    {
        $this->markTestSkipped('TODO');
    }

    public function testPrime_cache_keys()
    {
        $this->markTestSkipped('TODO');
    }
}
